openMF/mifos-mobile-cn

COMMIT_STYLE.md, CONTRIBUTING.md, README.md
=> feat:added readme, commit_style and contribuitng guidelines

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/dashboard/DashboardFragment.kt
Fixes #17
Please Add Screenshots If there are any UI changes.
=> fix: added account link in drawer and fixed previous title bar appearance

LICENSE.md, README.md
=> feat: added license

.travis.yml
=> feat:added travis

README.md
=> refactor: typo in readme.md

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginActivity.kt
=> fix: added error messages in LoginActivity

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginContract.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginPresenter.kt
=> fix: added invalid credentials message to LoginActivity

app/src/main/kotlin/org/mifos/mobile/cn/data/models/product/ProductPage.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/FakeJsonName.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/FakeRemoteDataSource.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/TestDataFactory.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ActivityComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/ProductAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/products/ProductContracts.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/products/ProductFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/products/ProductPresenter.kt, app/src/main/res/drawable/ic_products_black_24dp.xml, app/src/main/res/drawable/ic_search_black_24dp.xml, app/src/main/res/layout/fragment_product.xml, app/src/main/res/layout/item_product.xml, app/src/main/res/menu/menu_nav_drawer.xml, app/src/main/res/menu/menu_product_search.xml, app/src/main/res/values/strings.xml, app/src/main/resources/productPage.json
Fixes #48 
Please Add Screenshots If there are any UI changes.
=> feat: Product list

app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ActivityComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/LoanApplicationStepAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/LoanDebtIncomeAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/LoanDebtIncome/LoanDebtIncomeFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/OnNavigationBarListener.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/loanActivity/LoanApplicationActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/loanDetails/LoanDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/loancosigner/LoanCosignerFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/review/AddLoanReviewFragment.kt, app/src/main/res/drawable/review_circle_bg.xml, app/src/main/res/layout/fragment_add_loan_review.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles_text.xml, app/src/main/res/values/styles_view.xml
Fixes #26 
Please Add Screenshots If there are any UI changes.
=> feat: added Loan Review page

app/src/main/AndroidManifest.xml, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerDetails/CustomerDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerProfile/CustomerProfileActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerProfile/CustomerProfileContract.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/ConstantKeys.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/Utils.kt, app/src/main/res/layout/activity_customer_profile.xml, app/src/main/res/menu/menu_customer_profile.xml, app/src/main/res/values/strings.xml
=> feat added Customer Profile

app/src/main/kotlin/org/mifos/mobile/cn/data/models/customer/AccountEntriesPage.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/models/customer/AccountEntry.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/FakeJsonName.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/FakeRemoteDataSource.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/TestDataFactory.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ActivityComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/RecentTransactionsAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/dashboard/DashboardFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/recentTransactions/RecentTransactionsContracts.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/recentTransactions/RecentTransactionsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/recentTransactions/RecentTransactionsPresenter.kt, app/src/main/res/layout/fragment_recent_transactions.xml, app/src/main/res/layout/item_recent_transactions.xml, app/src/main/res/menu/menu_transactions_search.xml, app/src/main/res/values/strings.xml, app/src/main/resources/entries.json
Fixes #46 
Please Add Screenshots If there are any UI changes.
=> feat: added recent transactions

app/src/commonTest/kotlin/org/mifos/mobile/cn/FakeRemoteDataSource.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/datamanager/DataManagerCustomer.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/local/DatabaseHelperCustomer.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/models/customer/Customer.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/models/customer/DateOfBirth.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/models/customer/identification/Identification.kt, app/src/main/kotlin/org/mifos/mobile/cn/exceptions/ExceptionStatusCode.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/TestDataFactory.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ActivityComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ApplicationComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ConfigPersistentComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/DepositAccountListAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/IdentificationsAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/accounts/AccountsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerActivities/CustomerActivitiesFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerDetails/CustomerDetailsActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/identificationdetails/IdentificationDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/BaseFragmentDebtIncome.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/CircularImageView.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/ConstantKeys.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/ImageLoaderUtils.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/Network.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/views/ViewBehavior.kt
=> chore:warning and code cleaning

app/src/main/kotlin/org/mifos/mobile/cn/data/datamanager/DataManagerDepositDetails.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/remote/BaseApiManager.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/services/DepositService.kt, app/src/main/kotlin/org/mifos/mobile/cn/fakesource/FakeRemoteDataSource.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ActivityComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ApplicationComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/adapter/DepositAccountListAdapter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/accounts/AccountsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerDepositDetails/CustomerDepositDetailsContracts.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerDepositDetails/CustomerDepositDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerDepositDetails/CustomerDepositDetailsPresenter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/ConstantKeys.kt, app/src/main/res/drawable-v24/ic_people_black_24dp.xml, app/src/main/res/layout/fragment_customer_deposit_details.xml, app/src/main/res/values/strings.xml
=> feat: deposit details

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/accounts/AccountsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerAccounts/CustomerAccountFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/dashboard/DashboardFragment.kt
Fixes #58 
**Before**
**After**
=> fix: Deposit tab comes first in Customer Accounts

README.md
=> chore: added gitter shield and travis shield in README.md

app/src/main/res/layout/item_recent_transactions.xml
=> removed harcoded text

app/src/main/res/values/strings.xml
=> added 'Review' item

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/settings/SettingsFragment.kt, app/src/main/res/layout/fragment_settings.xml
=> Handled Settings click in Nav drawer and seperate fragment for it

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt
=> Added: Toast showing successful logout

app/src/main/res/values/colors.xml
I noticed that a lot of time same colors were added in different PRs (#110, #112, #115, #117, #118, #119), therefore to avoid a lot of merge conflicts, I have added all the necessary colors in this PR.
If this gets merged, we would be able to edit previous redesign PRs according to it.
=> redesign: Added all the necessary colors involved in redesign

app/src/main/res/values/styles.xml
I noticed that the same changes were made in different PRs (#110, #112, #115, #117, #118, #119), therefore to avoid a lot of merge conflicts, I think it would be better to merge this individually and remove this change from those PRs.
If this gets merged, we would be able to edit previous redesign PRs according to it.
#
=> redesign: added material style component

app/src/main/res/values/styles.xml
Fixes #111 
This PR fixes the UI inconsistencies that are in the logout alert dialog box due to the addition of #122 
##
=> fix: logout dialog box UI inconsistencies

.github/PULL_REQUEST_TEMPLATE.md
Improved the existing Pull Request Template.
**While writing the PR:**
<br>
**Preview of the PR:**
=> Feat: Improved the PR Template

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/DashboardActivity.kt, app/src/main/res/values/strings.xml
=> Fix: Share Button working

.github/ISSUE_TEMPLATE.md
Improved the existing Issue Template
**While writing the issue:**
<br>
**Preview of the issue:**
=> Fix: Improved the Issue Template

app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/dashboard/DashboardFragment.kt
=> Add functionality to SwipeRefreshLayout

app/src/main/AndroidManifest.xml, app/src/main/kotlin/org/mifos/mobile/cn/data/datamanager/DataManagerAuth.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/local/PreferenceKey.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/local/PreferencesHelper.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/remote/BaseUrl.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/remote/ConnectivityInterceptor.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/remote/MifosInterceptor.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/remote/MifosOkHttpClient.kt, app/src/main/kotlin/org/mifos/mobile/cn/data/services/AuthService.kt, app/src/main/kotlin/org/mifos/mobile/cn/injection/component/ApplicationComponent.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginActivity.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginContract.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/login/LoginPresenter.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/utils/ImageLoaderUtils.kt
Added support for demo  FineractCN instance hosted at buffalo.mifos.io
##
=> Support For Demo Instance

app/src/main/res/layout/fragment_profile.xml
=> Corrected Errors in Profile Fragment

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/kotlin/org/mifos/mobile/cn/ui/base/MifosBaseFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/Account.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/Home.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/Send.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/accountsFilter/AccountsFilterBottomSheet.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerAccounts/CustomerAccountFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/customerLoanDetails/CustomerLoanDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/identificationdetails/IdentificationDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/identificationlist/IdentificationsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/AddDebtIncomeBottomSheet.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/LoanDebtIncome/LoanDebtIncomeFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/loanDetails/LoanDetailsFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/mifos/loanApplication/loancosigner/LoanCosignerFragment.kt, app/src/main/kotlin/org/mifos/mobile/cn/ui/review/AddLoanReviewFragment.kt, app/src/main/res/layout/activity_send.xml, app/src/main/res/layout/content_fragment_dashboard.xml, app/src/main/res/values/strings.xml, build.gradle
<p align="center">
<p align="center">
<p align="center">
##
=> Hover SDK Implemented
